<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE properties [
    <!ELEMENT properties (property+)>
    <!ELEMENT property (name, location, price, size)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT size (#PCDATA)>
]>
<properties>
    <property>
        <name>House</name>
        <location>Mumbai</location>
        <price>500,000</price>
        <size>2000 sqft</size>
    </property>
    <property>
        <name>Apartment</name>
        <location>Satara</location>
        <price>300,000</price>
        <size>1200 sqft</size>
    </property>
    <property>
        <name>Villa</name>
        <location>Pune</location>
        <price>1,000,000</price>
        <size>5000 sqft</size>
    </property>
</properties>
